version: "3.8"

services:
  python: # Not adding image-name here because it is local
    container_name: "bike-python"
    build: "./"
    working_dir: "/bike/app"
    volumes:
      - "./app/:/bike/app"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - API_URL=http://express-server:1337/v1
      - PYTEST_ADDOPTS=-p no:cacheprovider
    restart:
      "on-failure"
