FROM python:3.10.12-slim

WORKDIR /bike/app

COPY ./app/requirements-prod.txt ./
RUN pip install --no-cache-dir -r requirements-prod.txt

COPY ./app/routes ./routes
COPY ./app/src ./src
COPY ./app/to_simulation ./to_simulation
COPY ./app/app.py ./

CMD ["python", "app.py"]
