version: "3.8"

services:
  python: # Not adding image-name here because it is local
    container_name: "bike-python"
    build: "./"
    working_dir: "/bike/app"
    volumes:
      - "./app/:/bike/app"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    restart:
      "on-failure"
